### ISSUE TITLE
New Report: Valid from / Valid to date label and validation errors

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_frontend#101]
The valid from and valid to are both functioning improperly:
-first, the valid to IS NOT required...so it should not be validated as such and should not have an asterisk
-second, the validation of both is not correct:  
---valid from should be checked against the agency registration start and end dates.  Valid from should not be before the registration start date nor after the registration end date.
---valid to, when provided, should be checked only against the valid from date to ensure that it is later than the valid from date.

**Comment by ctueck** [comment]
To illustrate, this is the validation currently happening but should not:

![image](https://user-images.githubusercontent.com/37637883/39575039-6d641408-4ed9-11e8-8592-82439c23b28b.png)

**Comment by gygabor** [comment]
fixed it, please check it on the test server.

**Comment by Gyukat** [comment]
Didn't Josh fix this earlier?

**Comment by gygabor** [comment]
Yes I fixed it but I didn't know that the solution was good. Josh just said it was OK. Sorry
