### ISSUE TITLE
Webform - languages/countries

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_frontend#62]
The country on programme does not work. 

Languages on file works, but the assigned language "tag" is too short so many language names wrap.

Personally, I find this system of using a field to select the country name but then adding tags directly into the field weird.  I think if we want to use tags instead of properly filled fields to display the values, then we only need a "select box"---like the country filter on the institution list, but better :) ---  In this case, the box could be next to the "file languages" label and the tags can be arrayed horizontally (as now) beneath the label.  What do you think?  If this works, then it can be used for all of these types of fields.  If not, then I would simply be consistent and use field fields---an empty one can appear after each field is filled.

(Btw, the country select list on the institution popup/regular list should only list countries that we actually have in the system.)

**Comment by gygabor** [comment]
Hi, 

Do you think we should create a language table and a country table and the user could select languages/countries like "Browse Institutions" button works?

**Comment by Gyukat** [comment]
No, if I understand correctly that would be overkill.  I think that the file languages works more or less okay, but the display is wonky.  We should either decide to use tags, and then use them in a more standard way OR we can simply fill the field with the value selected and then make another empty field appear underneath.  (does that make sense?)

The programme country simply hasn't been activated yet.  It can work as a normal select...values can be all countries.

**Comment by JoshBone** [comment]
> the assigned language "tag" is too short so many language names wrap.

I was checking this and for me the select box is displaying the selected languages (even if they are long ones) pretty okay-ish. Can you send a screenshot via Slick and some info on which browser this occurs?

**Comment by ctueck** [comment]
On 
Firefox 59.0.2 (64-Bit) on macOS:

![grafik](https://user-images.githubusercontent.com/37637883/39376797-358a91c2-4a53-11e8-861c-9170571e64a7.png)
