### ISSUE TITLE
Webform - Repeating boxes overemphasised

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_frontend#67]
These are not very neat.  There is a difference between the boxes in Programme and the box in Core Data (different borders/slightly different way of acting/button in different place).  I think the boxes in Programme have one too many levels (there should be one box but there are two--a box in a box).

In general, these boxes are for less important data.  The formatting over-emphasises them.  

CHOICE:
-I would advise lightening up the borders, maybe thinner and only coloured on the top.
-Alternatively, we could have only the button and the box would appear only after it is clicked.  

Maybe I prefer the former, but only if the box is much lighter and takes up less space.

**Comment by JoshBone** [comment]
Before I start implement it...
What if the repeatable forms would look like this?
So the bounding box is constant and the fields are repeating inside the box...
Like this:
![screen shot 2018-04-29 at 00 03 44 1](https://user-images.githubusercontent.com/927344/39401234-f36e16a8-4b40-11e8-93e0-7be59f884878.png)

**Comment by Gyukat** [comment]
I like it as a concept, definitely, but the top and bottom still seem very "heavy" to me.

**Comment by JoshBone** [comment]
@Gyukat @ctueck / What do you think? I tried to use the same graphical elements + reduced the colours a bit...
