### ISSUE TITLE
Webform - Add ids to select values

### ISSUE THREAD

**Issue by Gyukat** [EQAR/eqar_frontend#73]
Add IDs to the list of STATUS, DECISIONS, ACTIVITIES.

It can look like this:

1 - part of obligatory system
2 - voluntary

**Comment by JoshBone** [comment]
Are we sure that we would like to this on the ReportForm and not to provide a menu with all these entries listed? Personally I think it looks a bit weird in a select box. @ctueck - How do you feel about this? 

![screen shot 2018-04-27 at 10 52 53](https://user-images.githubusercontent.com/927344/39353908-4b3df3b4-4a09-11e8-8f6d-d28f5e49cee6.png)


![screen shot 2018-04-27 at 10 53 04](https://user-images.githubusercontent.com/927344/39353869-3922bffc-4a09-11e8-8cf1-1e815a557466.png)

**Comment by ctueck** [comment]
I don't think we need a separate menu for this - the codes are basically constants and are explained in the documentation.

But I think the rationale was to make people used to the codes by also including them in the webform. I don't mind the look of it.

Anyway, not an urgent issue by any means as far as I'm concerned.

**Comment by Gyukat** [comment]
I like it better with the codes...so, yes, that is what I meant...the timing for implementation is up to you.

**Comment by JoshBone** [comment]
Done, but I leave it open because there is one more question.
The values in the select list were ordered alphabetically (activities, decision, status) - Should it be changed according to id?

**Comment by JoshBone** [comment]
Done!
