### ISSUE TITLE
Webform - retain uploaded file extension 

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_frontend#78]
For Report Files uploaded and having a file display name, the file is renamed to the display name.

In general, it should probably keep its actual name, but the real problem is that the extension disappears. The URL of the saved file then returns a generic `application/octet-stream` content-type and the browser doesn't handle the file properly.

**Comment by gygabor** [comment]
I talk with József maybe it's a backend bug.

**Comment by JoshBone** [comment]
@gygabor 
I think the problem exist here:
https://github.com/EQAR/eqar_frontend/blob/f10f04fb24fcd47302164d28f8c24c50e401d98d/src/views/ReportForm/Actions/sendFiles.js#L32

The endpoint always needs the original file_name. The display name should be sent with the language codes. So if you have a file: `example_report.pdf` and you have the display_name set up as `Some example report`, the display_name should be sent to the `submit/report/` endpoint in the report_files section and the file should be then put to /submit/reportfile/${file.id}/example_report.pdf

In the backend the file is getting a timestamp prefix.

I'll fix the file naming, please check that the display_name is submitted alongside the report_language.
