### ISSUE TITLE
Webform - date fields in older browser

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_frontend#79]
On slightly older browsers without full support for the `<input type="date">` field, the valid from/to date form fields are not very easy to use: there's no indication of the expected YYYY-MM-DD format.

**Comment by JoshBone** [comment]
Hi Colin,
Usually date entry is always a big question mark, how it should be done properly. 
Do you think using the airbnb date fields are a bit of an overkill? 
http://airbnb.io/react-dates/

The other idea is to used masked input fields to avoid bad data:
http://insin.github.io/react-maskedinput/
(obviously styled to the current template)

Which one you think would fit more?

**Comment by ctueck** [comment]
Hi Josh, the Airbnb thing indeed looks a bit like an overkill. :)

The masked input field looks okay, but I even think for a very immediate solution it would be enough to put YYYY-MM-DD there using the `placeholder` attribute - it seems it would show on older browsers, but recent ones with `type="date"` support would ignore it anyway
