### ISSUE TITLE
Institutions with old names show up multiple times

### ISSUE THREAD

**Issue by ctueck** [EQAR/eqar_frontend#81]
Institutions that have old name records show up several times in the reference list, pop up or search results.

Examples: DEQARINST1268 (University of Split) or DEQARINST1985 (Warsaw University), the latter one has 5 old names recorded, so it shows 5 times in the list.

**Comment by JoshBone** [comment]
I've checked these records in the admin.deqar.eu and I see only one instance...

**Comment by ctueck** [comment]
Strange, it really did show up several times before, but now it doesn't do anymore. :)
